[build]
  command = "npm run build"
  publish = "dist"

# Handle CORS issues by adding headers
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

# Add environment variables configuration
[build.environment]
  NODE_VERSION = "16"

# Add redirects for SPA - this is critical for handling routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
